### ISSUE TITLE
add coloring to get_landuse_geo_tile

### ISSUE THREAD

**Issue by slackzen** [edouardpoitras/osm-geo-mapper#1]
Adding color to the background using something like https://github.com/mackwic/colored would make tiles much more visually appealing.

**Comment by edouardpoitras** [comment]
I agree that the colors need work. Not sure the colored library is necessary. The [theme.rs](https://github.com/edouardpoitras/osm-geo-mapper/blob/master/src/viewer/theme.rs) file should be enough to customize the look-and-feel of any geotile - just a matter of putting in the time/effort to figuring out what combination of character, foreground, background, and modifier works best for each feature type. I'd like to eventually expose a config file for theme options.

**Comment by edouardpoitras** [comment]
Version 0.7.0 now has some more reasonable theme color defaults. Tweaking the theme will be an ongoing process - closing issue.
